version: "3"

services:
  go:
    build: .
    container_name: go
    restart: always
    networks:
      - backend
    env_file:
      - development.env
    # environment:
    #   DEBUG: "true"
  db:
    image: postgres:11-alpine
    container_name: db
    restart: always
    ports:
        - 5432
    environment:
        POSTGRES_PASSWORD: SuperSecret
    volumes:
        - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - backend

networks:
  backend:
