version: "3"

services:
  go:
    build: .
    container_name: go
    restart: always
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
    env_file:
      - development.env
    environment:
      # DEBUG: "true"
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: SuperSecret
  db:
    image: postgres:11-alpine
    container_name: db
    restart: always
    ports:
        - 5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: SuperSecret
    volumes:
        - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - backend
  dbadmin:
    image: adminer
    container_name: dbadmin
    restart: always
    ports:
      - 8080
    logging:
      driver: "none"
    links:
      - db
    networks:
      - backend

networks:
  backend:
