version: "3"

services:
  go:
    build: .
    container_name: go
    restart: always
    networks:
      - backend
    env_file:
      - development.env
    # environment:
    #   DEBUG: "true"

networks:
  backend:
