apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot-deployment
  labels:
    app: slackbot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: slackbot
  template:
    metadata:
      labels:
        app: slackbot
    spec:
      containers:
      - name: slackbot
        image: fejalish/flakbot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DEBUG
          value: "true"
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slackbot-secrets
              key: slack_bot_token
